---
# tasks file for ec2
#
#
#
#
- name: "Launching ec2-instance"
  ec2:
          key_name: "{{ key_name }}"
          instance_type: "{{ instance_type }}"
          image: "{{ image_id }}"
          wait: yes
          count: "{{ count }}"
          vpc_subnet_id: "{{ subnet_id }}"
          region: "{{ region }}"
          state: present
          assign_public_ip: yes
          group_id: "{{ sg_group_id }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          instance_tags:
                  Name: "{{ item }}"
  loop: "{{ OS_name }}"


